"""rtsp_warden.install

First-run setup: writes .env, creates database schema, creates admin user.

Designed to be scriptable (env var overrides for CI/Docker) but
interactive-first for humans.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from rich.console import Console

from .auth import generate_admin_password, generate_app_secret, hash_password
from .db.engine import reset_engine
from .db.schema import create_admin_user, ensure_schema

log = logging.getLogger(__name__)
console = Console()

ENV_EXAMPLE_CONTENT = """\
# rtsp-warden environment configuration
# Copy this to .env and fill in real values.
# .env is gitignored — never commit real secrets.

# ---- Database ----
# Default: SQLite at $XDG_DATA_HOME/rtsp-warden/warden.db (zero-config)
# To use PostgreSQL, uncomment the WARDEN_DB_URL line below and fill in:
# WARDEN_DB_URL=postgresql+psycopg2://warden:YOUR_PASSWORD@127.0.0.1:7777/warden

# ---- PostgreSQL connection (used by `rtsp-warden install` to build WARDEN_DB_URL) ----
POSTGRES_HOST="127.0.0.1"
POSTGRES_PORT="7777"
POSTGRES_USER="warden"
POSTGRES_PASSWORD="changeme"
POSTGRES_DB="warden"

# ---- Auth (filled in by `rtsp-warden install`) ----
WARDEN_ADMIN_USERNAME="admin"
WARDEN_ADMIN_PASSWORD="changeme"
WARDEN_SECRET="changeme"

# ---- Auth gating ----
# When true, /healthz, /status.json, /metrics require a valid session or API token.
# Default: true (set by `rtsp-warden install`).
# Set to false to disable auth on the health server (NOT recommended for production).
WARDEN_AUTH_ENABLED="true"

# When true, /healthz remains unauthenticated even if auth is enabled.
# Useful for k8s/Docker liveness probes.
WARDEN_AUTH_HEALTHZ_OPEN="false"
"""


@dataclass
class InstallResult:
    """Result of a successful install."""

    env_path: Path
    env_example_path: Path
    admin_username: str
    admin_password: str  # plain text — caller decides whether to print
    app_secret: str
    db_url: str
    db_backend: str


def _write_env_file(path: Path, lines: dict[str, str], header: str) -> None:
    """Write a .env file with KEY="VALUE" format."""
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    parts = [f"# Generated by rtsp-warden install on {now_str}"]
    for key, value in lines.items():
        parts.append(f'{key}="{value}"')
    path.write_text("\n".join(parts) + "\n", encoding="utf-8")


def _ensure_postgres_database(
    pg_host: str,
    pg_port: int,
    pg_user: str,
    pg_password: str,
    pg_database: str,
) -> None:
    """Connect to the PostgreSQL 'postgres' maintenance DB and create the
    target database if it doesn't exist.

    Uses psycopg2 directly (not SQLAlchemy) for the bootstrap connection.
    """
    try:
        import psycopg2
        from psycopg2 import sql as pg_sql
    except ImportError as e:
        raise RuntimeError(
            "psycopg2 is required for PostgreSQL installs. "
            "Install it with: pip install psycopg2-binary"
        ) from e

    # Connect directly via psycopg2 (not through SQLAlchemy) for CREATE DATABASE
    dsn = f"host={pg_host} port={pg_port} dbname=postgres user={pg_user} password={pg_password}"
    try:
        conn = psycopg2.connect(dsn)
    except psycopg2.OperationalError as e:
        raise RuntimeError(
            f"Cannot connect to PostgreSQL at {pg_host}:{pg_port} as {pg_user} "
            f"— check the server is running and credentials are correct.\n"
            f"Detail: {e}"
        ) from e

    conn.autocommit = True
    try:
        with conn.cursor() as cur:
            # Check if database exists (safe against injection via pg_sql.Identifier)
            cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (pg_database,))
            if cur.fetchone() is None:
                # Create database with proper identifier quoting
                cur.execute(pg_sql.SQL("CREATE DATABASE {}").format(pg_sql.Identifier(pg_database)))
                log.info("Created PostgreSQL database %r", pg_database)
            else:
                log.info("PostgreSQL database %r already exists", pg_database)
    finally:
        conn.close()


def _load_dotenv(path: Path) -> dict[str, str]:
    """Parse a simple KEY="VALUE" .env file. No dependency on python-dotenv."""
    env: dict[str, str] = {}
    if not path.exists():
        return env
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        env[key] = value
    return env


def run_install(
    *,
    target_dir: Path,
    db_backend: str = "sqlite",  # "sqlite" | "postgres"
    pg_host: str = "127.0.0.1",
    pg_port: int = 7777,
    pg_user: str = "warden",
    pg_password: str | None = None,  # if None, generate
    pg_database: str = "warden",
    admin_username: str = "admin",
    admin_password: str | None = None,  # if None, generate
    app_secret: str | None = None,  # if None, generate
    force: bool = False,  # overwrite .env / .env.example if they exist
) -> InstallResult:
    """Run the first-time install process.

    1. Generate secrets if not provided
    2. Write .env with real values
    3. Write .env.example with placeholders (if missing or force)
    4. Connect to DB, create schema, create admin user
    5. Return InstallResult
    """
    target_dir = Path(target_dir).resolve()
    env_path = target_dir / ".env"
    env_example_path = target_dir / ".env.example"

    # 1. Check for existing .env
    if env_path.exists() and not force:
        raise FileExistsError(f".env already exists at {env_path}. Use --force to overwrite.")

    # 2. Generate secrets
    if admin_password is None:
        admin_password = generate_admin_password()
    if app_secret is None:
        app_secret = generate_app_secret()
    if db_backend == "postgres" and pg_password is None:
        pg_password = generate_admin_password()

    # 3. Compute DB URL
    if db_backend == "sqlite":
        var_dir = target_dir / "var"
        var_dir.mkdir(parents=True, exist_ok=True)
        db_url = f"sqlite:///{var_dir}/warden.db"
    elif db_backend == "postgres":
        db_url = f"postgresql+psycopg2://{pg_user}:{pg_password}@{pg_host}:{pg_port}/{pg_database}"
    else:
        raise ValueError(f"Unknown db_backend: {db_backend!r}. Use 'sqlite' or 'postgres'.")

    # 4. Write .env
    env_lines: dict[str, str] = {}
    if db_backend == "postgres":
        env_lines["WARDEN_DB_URL"] = db_url
        env_lines["POSTGRES_HOST"] = pg_host
        env_lines["POSTGRES_PORT"] = str(pg_port)
        env_lines["POSTGRES_USER"] = pg_user
        env_lines["POSTGRES_PASSWORD"] = pg_password
        env_lines["POSTGRES_DB"] = pg_database
    else:
        env_lines["WARDEN_DB_URL"] = db_url

    env_lines["WARDEN_ADMIN_USERNAME"] = admin_username
    env_lines["WARDEN_ADMIN_PASSWORD"] = admin_password
    env_lines["WARDEN_SECRET"] = app_secret
    env_lines["WARDEN_AUTH_ENABLED"] = "true"
    env_lines["WARDEN_AUTH_HEALTHZ_OPEN"] = "false"

    _write_env_file(env_path, env_lines, header="rtsp-warden")
    log.info("Wrote %s", env_path)

    # 5. Write .env.example (if missing or force)
    if not env_example_path.exists() or force:
        env_example_path.write_text(ENV_EXAMPLE_CONTENT, encoding="utf-8")
        log.info("Wrote %s", env_example_path)

    # 6. Connect to DB and ensure schema
    # Reset any existing engine so we use our freshly-computed URL
    os.environ["WARDEN_DB_URL"] = db_url
    reset_engine()

    if db_backend == "postgres":
        _ensure_postgres_database(
            pg_host=pg_host,
            pg_port=pg_port,
            pg_user=pg_user,
            pg_password=pg_password,
            pg_database=pg_database,
        )

    # After potentially creating the PG database, reset engine again
    # so SQLAlchemy picks up the target database URL
    reset_engine()
    ensure_schema()
    log.info("Schema created (7 tables)")

    # 7. Create admin user
    create_admin_user(admin_username, hash_password(admin_password))
    log.info("Admin user %r created", admin_username)

    return InstallResult(
        env_path=env_path,
        env_example_path=env_example_path,
        admin_username=admin_username,
        admin_password=admin_password,
        app_secret=app_secret,
        db_url=db_url,
        db_backend=db_backend,
    )
